apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-controllers-prometheus-discovery
  labels:
    k8s-app: kube-controllers
spec:
  selector:
    openshift.io/component: controllers
    openshift.io/control-plane: true
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 8444
    targetPort: 8444
    protocol: TCP
