apiVersion: v1
data:
  config.yaml: ImF1dGhvcml6YXRpb24iOiAKICAicmVzb3VyY2VBdHRyaWJ1dGVzIjogCiAgICAiYXBpVmVyc2lvbiI6ICJ2MSIKICAgICJuYW1lc3BhY2UiOiAie3sgLlZhbHVlIH19IgogICAgInJlc291cmNlIjogIm5vZGUiCiAgICAic3VicmVzb3VyY2UiOiAibWV0cmljcyIKICAicmV3cml0ZXMiOiAKICAgICJieVF1ZXJ5UGFyYW1ldGVyIjogCiAgICAgICJuYW1lIjogIm5hbWVzcGFjZSI=
kind: Secret
metadata:
  labels:
    k8s-app: prometheus-k8s
  name: kube-rbac-proxy
  namespace: openshift-monitoring
type: Opaque
