apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-k8s
  labels:
    k8s-app: prometheus-k8s
spec:
  selector:
    matchLabels:
      k8s-app: prometheus-k8s
      prometheus: k8s
  namespaceSelector:
    matchNames:
    - this-namespace-is-automatically-replaced-at-runtime
  endpoints:
  - port: web
    interval: 30s
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      serverName: alertmanager-main
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
