apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator
  labels:
    k8s-app: prometheus-operator
spec:
  selector:
    matchLabels:
      k8s-app: prometheus-operator
  namespaceSelector:
    matchNames:
    - this-namespace-is-automatically-replaced-at-runtime
  endpoints:
  - port: http
    interval: 30s
