apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s
  labels:
    k8s-app: prometheus-k8s
    prometheus: k8s
    name: prometheus-k8s
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: prometheus-k8s-tls
spec:
  type: ClusterIP
  selector:
    app: prometheus
    prometheus: k8s
  ports:
  - name: web
    port: 9090
    targetPort: web
    protocol: TCP
