apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager
  labels:
    k8s-app: alertmanager
spec:
  selector:
    matchLabels:
      k8s-app: alertmanager
      alertmanager: main
  namespaceSelector:
    matchNames:
    - this-namespace-is-automatically-replaced-at-runtime
  endpoints:
  - port: web
    interval: 30s
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      serverName: server-name-replaced-at-runtime
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
