apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  labels:
    k8s-app: node-exporter
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: node-exporter
  namespaceSelector:
    matchNames:
    - this-namespace-is-automatically-replaced-at-runtime
  endpoints:
  - port: https
    scheme: https
    interval: 30s
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      serverName: server-name-replaced-at-runtime
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
