apiVersion: v1
kind: Route
metadata:
  name: prometheus-k8s
  namespace: openshift-monitoring
spec:
  port:
    targetPort: web
  tls:
    termination: Reencrypt
  to:
    kind: Service
    name: prometheus-k8s
