apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: kube-scheduler
  name: kube-scheduler
  namespace: openshift-monitoring
spec:
  endpoints:
  - interval: 30s
    port: https
    relabelings:
    - action: replace
      regex: (.+)(?::\d+)
      replacement: $1:10251
      sourceLabels:
      - __address__
      targetLabel: __address__
  jobLabel: null
  namespaceSelector:
    matchNames:
    - openshift-kube-scheduler
  selector: {}
