apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: prometheus-k8s-tls
  labels:
    prometheus: k8s
  name: prometheus-k8s
  namespace: openshift-monitoring
spec:
  ports:
  - name: web
    port: 9091
    targetPort: web
  - name: tenancy
    port: 9092
    targetPort: tenancy
  - name: grpc
    port: 10901
    targetPort: 10901
  selector:
    app: prometheus
    prometheus: k8s
  sessionAffinity: ClientIP
  type: ClusterIP
