apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: main
  labels:
    k8s-app: alertmanager
    alertmanager: main
spec:
  replicas: 2
  version: v0.14.0
  serviceAccountName: alertmanager-main
  securityContext: {}
  resources:
    requests:
      memory: 40Mi
      cpu: 50m
  secrets:
  - alertmanager-main-tls
  - alertmanager-main-proxy
  listenLocal: true
  containers:
  - name: alertmanager-proxy
    image: "openshift/oauth-proxy:v1.1.0"
    resources: {}
    ports:
    - containerPort: 9094
      name: web
    args:
    - -provider=openshift
    - -https-address=:9094
    - -http-address=
    - -email-domain=*
    - -upstream=http://localhost:9093
    - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
    - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}'
    - -tls-cert=/etc/tls/private/tls.crt
    - -tls-key=/etc/tls/private/tls.key
    - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
    - -cookie-secret-file=/etc/proxy/secrets/session_secret
    - -openshift-service-account=alertmanager-main
    - -openshift-ca=/etc/pki/tls/cert.pem
    - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    - -skip-auth-regex=^/metrics
    volumeMounts:
    - mountPath: /etc/tls/private
      name: secret-alertmanager-main-tls
    - mountPath: /etc/proxy/secrets
      name: secret-alertmanager-main-proxy
