apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: alertmanager-main
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alertmanager-main
subjects:
- kind: ServiceAccount
  name: alertmanager-main
  namespace: this-namespace-is-automatically-replaced-at-runtime
