apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: alertmanager-access
  namespace: openshift-monitoring
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  verbs:
  - get
