apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: alertmanager-main-tls
  labels:
    alertmanager: main
  name: alertmanager-main
  namespace: openshift-monitoring
spec:
  ports:
  - name: web
    port: 9094
    targetPort: web
  selector:
    alertmanager: main
    app: alertmanager
  type: ClusterIP
