sudo: required
language: go
go:
- "1.10"
services:
- docker
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y python-pip
- sudo pip install yamllint
jobs:
  include:
  - script: yamllint .
  - stage: Build
    script: make build
  - script: make generate && git diff --exit-code
