sudo: required
language: go
go:
- "1.10"
services:
- docker
jobs:
  include:
  - script: ./hack/yamllint.sh .
  - script: make test-unit
  - stage: Build
    script: make dependencies build
  - script: make generate && git diff --exit-code
  - script: make container
