apiVersion: v1
data:
  grafana.ini: W2F1dGhdCmRpc2FibGVfbG9naW5fZm9ybSA9IHRydWUKZGlzYWJsZV9zaWdub3V0X21lbnUgPSB0cnVlClthdXRoLmJhc2ljXQplbmFibGVkID0gZmFsc2UKW2F1dGgucHJveHldCmF1dG9fc2lnbl91cCA9IHRydWUKZW5hYmxlZCA9IHRydWUKaGVhZGVyX25hbWUgPSBYLUZvcndhcmRlZC1Vc2VyCltwYXRoc10KZGF0YSA9IC92YXIvbGliL2dyYWZhbmEKbG9ncyA9IC92YXIvbGliL2dyYWZhbmEvbG9ncwpwbHVnaW5zID0gL3Zhci9saWIvZ3JhZmFuYS9wbHVnaW5zCnByb3Zpc2lvbmluZyA9IC9ldGMvZ3JhZmFuYS9wcm92aXNpb25pbmcKW3NlY3VyaXR5XQpjb29raWVfc2VjdXJlID0gdHJ1ZQpbc2VydmVyXQpodHRwX2FkZHIgPSAxMjcuMC4wLjEKaHR0cF9wb3J0ID0gMzAwMQo=
kind: Secret
metadata:
  name: grafana-config
  namespace: openshift-monitoring
type: Opaque
