apiVersion: v1
data:
  grafana.ini: |
    [auth]
    disable_login_form = true
    disable_signout_menu = true
    [auth.basic]
    enabled = false
    [auth.proxy]
    auto_sign_up = true
    enabled = true
    header_name = X-Forwarded-User
    [server]
    http_addr = 127.0.0.1
    http_port = 3001
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: openshift-monitoring
