apiVersion: v1
data:
  grafana.ini: W2F1dGhdCmRpc2FibGVfbG9naW5fZm9ybSA9IHRydWUKZGlzYWJsZV9zaWdub3V0X21lbnUgPSB0cnVlClthdXRoLmJhc2ljXQplbmFibGVkID0gZmFsc2UKW2F1dGgucHJveHldCmF1dG9fc2lnbl91cCA9IHRydWUKZW5hYmxlZCA9IHRydWUKaGVhZGVyX25hbWUgPSBYLUZvcndhcmRlZC1Vc2VyCltzZXJ2ZXJdCmh0dHBfYWRkciA9IDEyNy4wLjAuMQpodHRwX3BvcnQgPSAzMDAxCg==
kind: Secret
metadata:
  name: grafana-config
  namespace: openshift-monitoring
type: Opaque
