apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-monitoring-operator
  namespace: openshift-monitoring
  labels:
    app: cluster-monitoring-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-monitoring-operator
  template:
    metadata:
      labels:
        app: cluster-monitoring-operator
    spec:
      serviceAccountName: cluster-monitoring-operator
      containers:
      - image: docker.io/openshift/origin-cluster-monitoring-operator:latest
        name: cluster-monitoring-operator
        args:
        - "-namespace=openshift-monitoring"
        - "-configmap=cluster-monitoring-config"
        - "-logtostderr=true"
        - "-v=4"
        - "-images=prometheus-operator=docker.io/openshift/origin-prometheus-operator:latest"
        - "-images=prometheus-config-reloader=docker.io/openshift/origin-prometheus-config-reloader:latest"
        - "-images=config-reloader=docker.io/openshift/origin-configmap-reload:latest"
        - "-images=prometheus=docker.io/openshift/origin-prometheus:latest"
        - "-images=alertmanager=docker.io/openshift/origin-prometheus-alertmanager:latest"
        - "-images=grafana=docker.io/grafana/grafana:latest"
        - "-images=oauth-proxy=docker.io/openshift/oauth-proxy:latest"
        - "-images=node-exporter=docker.io/openshift/origin-prometheus-alertmanager:latest"
        - "-images=kube-state-metrics=docker.io/openshift/origin-kube-state-metrics:latest"
        - "-images=kube-rbac-proxy=docker.io/openshift/origin-kube-rbac-proxy:latest"
        - "-images=telemeter-client=docker.io/openshift/origin-telemeter:latest"
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 20m
            memory: 50Mi
          requests:
            cpu: 20m
            memory: 50Mi
