apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: openshift-cluster-monitoring
  namespace: openshift-monitoring
spec:
  selector:
    openshift.io/cluster-monitoring: "true"
