apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |+
    prometheusOperator:
      baseImage: quay.io/brancz/prometheus-operator-openshift
      prometheusConfigReloaderBaseImage: quay.io/brancz/prometheus-config-reloader-openshift
      configReloaderBaseImage: quay.io/brancz/configmap-reload-openshift
    prometheusK8s:
      baseImage: openshift/prometheus
    alertmanagerMain:
      baseImage: openshift/prometheus-alertmanager
    nodeExporter:
      baseImage: openshift/prometheus-node-exporter
    kubeRbacProxy:
      baseImage: quay.io/brancz/kube-rbac-proxy-openshift
    kubeStateMetrics:
      baseImage: quay.io/brancz/kube-state-metrics-openshift
