apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: node-exporter
  name: node-exporter
  namespace: openshift-monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/prometheus-serving-certs-ca-bundle/service-ca.crt
      serverName: server-name-replaced-at-runtime
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: node-exporter
