apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: cluster-monitoring-operator
  name: cluster-monitoring-operator
  namespace: openshift-monitoring
spec:
  endpoints:
  - port: http
  selector:
    matchLabels:
      app: cluster-monitoring-operator
