apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-user-workload-config
  namespace: openshift-user-workload-monitoring
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
