apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: prometheus-user-workload-tls
  labels:
    prometheus: user-workload
  name: prometheus-user-workload
  namespace: openshift-user-workload-monitoring
spec:
  ports:
  - name: metrics
    port: 9091
    targetPort: metrics
  selector:
    app: prometheus
    prometheus: user-workload
  sessionAffinity: ClientIP
  type: ClusterIP
