apiVersion: v1
kind: Route
metadata:
  name: thanos-querier
  namespace: openshift-monitoring
spec:
  port:
    targetPort: web
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: Reencrypt
  to:
    kind: Service
    name: thanos-querier
