apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: thanos-querier-tls
  labels:
    app.kubernetes.io/name: thanos-querier
  name: thanos-querier
  namespace: openshift-monitoring
spec:
  ports:
  - name: web
    port: 9091
    targetPort: web
  - name: tenancy
    port: 9092
    targetPort: tenancy
  selector:
    app.kubernetes.io/name: thanos-querier
  type: ClusterIP
