apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: thanos-ruler-tls
  labels:
    app.kubernetes.io/name: user-workload
  name: thanos-ruler-user-workload
  namespace: openshift-user-workload-monitoring
spec:
  ports:
  - name: web
    port: 9091
    targetPort: web
  selector:
    app: thanos-ruler
    thanos-ruler: user-workload
  sessionAffinity: ClientIP
  type: ClusterIP
